### ISSUE TITLE
Failure in rspecs

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rails-keyserver#23]
See GitHub Actions.

```
ArgumentError: wrong number of arguments (given 0, expected 1)
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/bundler/gems/activeuuid-8d8accd7017c/lib/activeuuid/patches.rb:175:in `initialize_type_map'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:526:in `reload_type_map'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:166:in `clear_cache!'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:394:in `disconnect!'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:103:in `disconnect!'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `block (3 levels) in disconnect'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `each'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `block (2 levels) in disconnect'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:449:in `block in disconnect'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:697:in `block in with_exclusively_acquired_all_connections'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:772:in `with_new_connections_blocked'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:695:in `with_exclusively_acquired_all_connections'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `disconnect'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:470:in `disconnect!'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1050:in `remove_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:977:in `establish_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:60:in `establish_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/bundler/gems/activeuuid-8d8accd7017c/lib/activeuuid/patches.rb:190:in `establish_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/tasks/sqlite_database_tasks.rb:6:in `establish_connection'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/tasks/sqlite_database_tasks.rb:15:in `create'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/tasks/sqlite_database_tasks.rb:33:in `purge'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:209:in `purge'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:339:in `block (3 levels) in <top (required)>'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:345:in `block (3 levels) in <top (required)>'
/home/runner/work/rails-keyserver/rails-keyserver/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.6.8/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.6.8/x64/bin/bundle:23:in `<main>'
Tasks: TOP => app:db:test:load => app:db:test:purge
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```

_Originally posted by @CAMOBAP in https://github.com/riboseinc/rails-keyserver/issues/22#issuecomment-886687149_

**Comment by CAMOBAP** [comment]
Make sense to simplify ruby-rnp installation process first in https://github.com/rnpgp/ruby-rnp/issues/76

**Comment by ronaldtse** [comment]
Thanks @camobap! Agree.
